### ISSUE TITLE
Examples don't work correctly.

### ISSUE THREAD

**Issue by lklanswer** [SerbanL/Boris2#12]
I am using v3.80 (22nd February 2023).
But examples cannot run properly. For example, `$BorisLin/Boris_Data/Examples/Tutorial 0/hysteresis.py`.
I found this command
```
Py = ns.Ferromagnet([160e-9, 80e-9, 10e-9], [5e-9])
```
causes an error
```
ERROR : Parameter out of bounds. Info : Parameter 1, Min : -1m, -1m, -1m; -1000mm, -1000mm, -1000mm to Max : -1m, -1m, -1m; 1m, 1m, 1m
```
which can be corrected by replacing the command with
```
Py = ns.Ferromagnet([-160e-9, -80e-9, -10e-9, 160e-9, 80e-9, 10e-9], [5e-9])
```

**Comment by SerbanL** [comment]
I don't know what's causing this, but this works on all the setups I've tested.
The solution you suggested doubles all mesh dimension, so instead you could try Py = ns.Ferromagnet([0, 0, 0, 160e-9, 80e-9, 10e-9], [5e-9])

**Comment by lklanswer** [comment]
Thank you. I'll try it. I don't know whether the error is caused by my low python version.
