### ISSUE TITLE
GPU select

### ISSUE THREAD

**Issue by MateuszZelent** [SerbanL/Boris2#2]
Hi,

I would like to suggest that the user should be able to choose the GPU on which the calculations will be performed. 

Regards,
Mateusz

**Comment by SerbanL** [comment]
Hi Mateusz,

not sure I understand, do you mean if you have more than one GPU on the same PC you want to choose which one to execute on?

Currently the program launcher on Windows detects the GPU CUDA compute version and launches the right executable compiled for that version - btw CUDA compute 8.0 (Ampere) cards are out now so will include this in the next release version.

Regards,
Serban

**Comment by MateuszZelent** [comment]
For example, I have 4 RTX 2080TI in one machine, and I cannot specify on which card the calculations should be executed. 

I tried to use Windows "Render OpenGL on", but it doesn't work.

**Comment by SerbanL** [comment]
Aha, I understand. Yes that should be straightforward to do, I'll include it in the next release.

One related thing I have on my to do list is multi-GPU computations. Unfortunately this one is not straightforward at all, even though the hardest part (multi-GPU FFTs) is already in the CUDA library, but I'm hoping to get around to it soon.

**Comment by MateuszZelent** [comment]
Thank you!

I have Tesla V100 with 2-way or 4-way NVLINK so I can help you to test it. Let me know If you will need anything.

**Comment by SerbanL** [comment]
Done, pushed latest update. Will take maybe 2 more weeks before I release a new point version, but if you want you can compile the code on Linux to test. Will also need to update manual.
To select GPU use the selectcudadevice command with device number (0/1/2/3...). After selecting device you still need to switch cuda on as cuda 1.
You can also change the server port using the serverport command. Then use the updated NetSock.py module to control multiple Boris instances from a single Python script (make an NSClient object for each port), each running on a different GPU.

**Comment by MateuszZelent** [comment]
@SerbanL great! Thank you. I'm waiting for the release!
