### ISSUE TITLE
Asynchronous data saving 

### ISSUE THREAD

**Issue by MateuszZelent** [SerbanL/Boris2#3]
Hi,

I have found one more issue - I think in Boris is missing asynchronous data saving procedure -  

![image](https://user-images.githubusercontent.com/16208378/96597617-5014f800-12ee-11eb-969c-51a04791bec6.png)

I noticed that when Boris needs to save a lot of data on the disk (and there is a connection problem or the disk is busy), calculations are stopped. Is writing files in Boris asynchronous (e.g. writing files on disk is queued in RAM and a separate process is responsible for writing them on disk)? If not, maybe it is worth to do it?

**Comment by SerbanL** [comment]
No, currently saving is done on the same thread. I'll look into this for next version as well.

I think this shouldn't be difficult, data writing functions can be called on a separate thread with a non-blocking call, launched from the thread which runs the computations, and with mutex access to ensure completion before it is called again. Should be of benefit for CUDA simulations, but probably not for CPU-based simulations.

**Comment by MateuszZelent** [comment]
Yes, you are right, so maybe it could be an option. 

Thanks!

**Comment by SerbanL** [comment]
Done now, including asynchronous display refresh. Asynchronous data saving applicable to all data outputs which can be added to simulation schedule, not to other types of data outputs, e.g. saving ovf2 files. Benchmarking tests showed significant speed improvements for both cuda 0/1 simulations with frequent data saves. Will push to master branch soon, but if I've missed something when you test it let me know.
