### ISSUE TITLE
Spherical shell

### ISSUE THREAD

**Issue by Ahsanu8** [SerbanL/Boris2#5]
Hi, do you have a spherical shell option in Boris? 

Like you do have the one Shape.ellipsoid. But I am not sure if you have an option for Shape.shell or anything like that?

Kind Regards

**Comment by SerbanL** [comment]
Sphere is a special case of ellipsoid with the 3 dimensions equal. You can subtract objects, so subtract one sphere from another to get a shell. See manual for similar examples.
